[package]
name = "aliasx"
version = "0.1.2"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
execute = "0.2.13"
fuzzy-select = "0.1.3"
serde = { version="1.0.228", features = ["derive"] }
serde_json5 = "0.2.1"
serde_yaml = "0.9.34"
